
http://localhost:3000/params/1

###

http://localhost:3000/params/1


###

http://localhost:8084/rest/api/protheus/session/v1/defaults

###

http://localhost:8084/rest/tabprotthf/tables?page=50
###

http://localhost:8084/rest/tabprotthf/params?page=50

###

http://localhost:8084/rest/tabprotthf/fields?page=50

