module.exports = [
  { name: "X3_ARQUIVO", canFilter: true },
  "X3_ORDEM",
  { name: "X3_CAMPO", canFilter: true },
  "X3_TIPO",
  { name: "X3_TITULO", canFilter: true },
  { name: "X3_DESCRIC", canFilter: true },
  "X3_PICTURE",
  "X3_VALID",
  "X3_RELACAO",
  "X3_F3",
  "X3_RESERV",
  "X3_TRIGGER",
  "X3_PROPRI",
  "X3_BROWSE",
  "X3_VISUAL",
  "X3_CONTEXT",
  "X3_OBRIGAT",
  "X3_VLDUSER",
  "X3_CBOX",
  "X3_PICTVAR",
  "X3_WHEN",
  "X3_INIBRW",
  "X3_GRPSXG",
  "X3_FOLDER",
  { name: "X3_TAMANHO", type: "N" },
  { name: "X3_DECIMAL", type: "N" }
];
