# Imagem com um banco PostgreSQL inicializado com a versão 12.1.17
FROM docker.totvs.io/dcp/database

#TODO: Conectar no banco e apagar as outras tabelas
#TODO: Criar a imagem e o Docker compose para subir as máquinas